FROM gradle:8.10.1-jdk21

COPY . /home/gradle/src
WORKDIR /home/gradle/src

RUN ./gradlew build

EXPOSE ${APP_PORT}

ENTRYPOINT ["java", "-jar", "$(ls /home/gradle/src/build/libs/*.jar | tail -n 1)"]
