name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      pull-requests: write


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Clean Gradle
        run: ./gradlew clean

      - name: Coverage
        run: ./gradlew koverVerify

      - name: Formatting/Lint
        run: ./gradlew ktlintCheck
        
      - name: Tests
        run: ./gradlew test

      - name: Auto-merge if approved and passing
        if: ${{ github.event.pull_request.mergeable == true && github.event.pull_request.reviewDecision == 'approved' }}
        run: gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}